# Generated by Django 3.1.3 on 2020-11-18 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc', '0002_auto_20201117_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateUser',
            new_name='EmployeUser',
        ),
    ]
