# Generated by Django 3.1.3 on 2020-11-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('acc', '0005_auto_20201118_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='type_user',
        ),
    ]
