# Generated by Django 3.1.3 on 2020-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0009_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(),
        ),
    ]
